FROM postgres:16.3
ENV POSTGRES_USER=dbuser
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=datab
ENV PGDATA=/var/lib/postgresql/data/pgdata
EXPOSE 5432

# docker build -t postgresdk:2.0 .
# docker run -d -p 5432:5432 postgresdk:2.0