
services:
  postgres:
    build: ../
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data


  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    develop:
      watch:
        - path: .
          action: sync
          target: .

    


